name: newupdate
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
  provider: ^6.0.5
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_auth: ^4.15.3
  fluttertoast: ^8.2.2
  pdf: ^3.10.4
  syncfusion_flutter_pdf: ^24.1.43
  open_file: ^3.3.2
  printing: ^5.11.0
  image_picker: ^1.0.4
  cloud_functions: ^4.4.1
  firebase_analytics: ^10.5.0
  firebase_app_check: ^0.2.0
  firebase_crashlytics: ^3.3.6
  firebase_dynamic_links: ^5.3.6
  firebase_messaging: ^14.6.8
  firebase_performance: ^0.9.2+6
  firebase_remote_config: ^4.2.6
  
# pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"


  flutter_lints: ^3.0.1
  intl: ^0.18.0
  path: ^1.8.3
flutter:
  uses-material-design: true
  
fonts:
    family: Montserrat
    fonts:
      - asset: assets/open-sans.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/politicalappslogo.jpg"

assets:
  - image/assets/DEEPAK.jpg

